[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = ""
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build && npx pnpm run build:blog"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
